apiVersion: v1
kind: Pod
metadata:
  name: azure-vote-back
  labels:
    app: azure-vote-back
spec:
  containers:
    - name: sql_dat_container
      image: sql_dat
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
      ports:
      - name: web
        containerPort: 5050