set identity_insert [dbo].[LoginNews] on

insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (1, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/20201208.jpg', N'https://upclear.com/upclears-growth-report-looking-ahead-to-2021/', N'UpClear''s 2020 Growth Report', 1, CAST(N'2020-12-08T10:18:09.617' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (2, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/20201207.jpg', N'https://upclear.com/events/upclear-hosting-share-group-at-consumer-goods-sales-marketing-summit/', N'UpClear Hosting RGM Share Group at Consumer Goods Sales and Marketing Summit', 1, CAST(N'2020-12-08T10:15:20.503' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (3, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/20201008-min.jpg', N'https://upclear.com/events/upclear-sponsors-analytics-unite-2020/', N'UpClear to sponsor a Share Group at Analytics Unite 2020. Join us on Thursday, October 8th at 12:05 pm EST', 1, CAST(N'2020-10-08T10:27:56.020' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (4, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/20200723.jpg', N'https://consumergoods.com/ris-cgt-analytics-study-2020', N'UpClear, a proud sponsor of the 2020 Retail & Consumer Goods Analytics Study', 1, CAST(N'2020-07-23T10:35:39.150' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (5, N'https://upclearstoragedev.blob.core.windows.net/loginnewsimage/WebinarAX2.png', N'https://upclear.com/events/upclear-to-host-rgm-sharegroup-at-cgts-analytics-unite-on-may-19th/', N'Webinar Advanced Analytics -  Wed 19th May 12.30pm EST', 1, CAST(N'2021-05-09T22:13:15.683' as DateTime), N'tech@upclear.com', CAST(N'2021-05-10T13:45:46.467' as DateTime), N'tech@upclear.com')
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (6, N'https://upclearstoragedev.blob.core.windows.net/loginnewsimage/WebinarDSD3.png', N'https://upclear.com/events/upclear-webinar-on-dsd-featuring-utz-quality-foods-and-vita-coco/', N'Webinar RGM for DSD -   Wed 12th May 2pm EST', 1, CAST(N'2021-05-09T22:14:04.530' as DateTime), N'tech@upclear.com', CAST(N'2021-05-09T22:32:26.997' as DateTime), N'tech@upclear.com')
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (8, N'https://upclearstoragedev.blob.core.windows.net/loginnewsimage/Cleartalk.jpg', N'https://upclear.com/events/join-us-friday-june-18th-for-cleartalk-live/', N'Join us for ClearTalk Live this Friday at June 18th at 1:00 pm EST', 1, CAST(N'2021-06-16T17:32:09.120' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (9, N'https://upclearstoragedev.blob.core.windows.net/loginnewsimage/IE11end.jpg', N'https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666', N'Microsoft 365 apps say farewell to Internet Explorer 11', 1, CAST(N'2021-08-11T12:55:03.700' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (10, N'https://upclearstoragedev.blob.core.windows.net/loginnewsimage/DairyWebinar.png', N'https://upclear.com/news-and-events/the-promotional-lifecycle-for-dairy/', N'UpClear hosting webinar on Promotion Lifecycle: Planning, focused on the Dairy category. Wednesday, 7th Oct - 1 pm EST', 1, CAST(N'2021-09-14T21:10:50.280' as DateTime), N'tech@upclear.com', CAST(N'2021-09-14T21:13:00.897' as DateTime), N'tech@upclear.com')
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (11, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/OnePercent.png', N'https://upclear.com/news-and-events/upclear-joins-1-percent-for-the-planet/', N'UpClear Joins 1% for the Planet', 1, CAST(N'2022-02-03T15:30:04.557' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (12, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/Razom%20logo.png', N'https://www.linkedin.com/feed/update/urn:li:activity:6905182377665261568/', N'UpClear supports Razom for Ukraine relief', 1, CAST(N'2022-03-03T16:28:49.290' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (13, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/Nissin.png', N'https://www.linkedin.com/posts/upclear_nissin-foods-selects-upclear-for-tpm-in-the-activity-6907812238498103296-vWnv', N'Nissin Foods selects BluePlanner for TPM in the USA', 1, CAST(N'2022-03-10T23:07:39.757' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (14, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/Twinings.jpg', N'https://www.linkedin.com/posts/upclear_twinings-expands-blueplanner-tpm-to-north-activity-6910214087469596672-C755?utm_source=linkedin_share&utm_medium=member_desktop_web', N'Twinings USA deploys BluePlanner', 1, CAST(N'2022-03-18T14:07:15.847' as DateTime), N'tech@upclear.com', CAST(N'2022-03-18T14:33:41.533' as DateTime), N'tech@upclear.com')
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (15, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/SE-Asia2.png', N'https://www.linkedin.com/posts/upclear_upclear-tpm-in-southeast-asia-understanding-activity-6912114695759900672-n2EG?utm_source=linkedin_share&utm_medium=member_desktop_web', N'TPM in Southeast Asia: Understanding and Winning Across a Diverse Set of Markets', 1, CAST(N'2022-03-24T20:34:59.233' as DateTime), N'tech@upclear.com', null, null)
insert [dbo].[LoginNews] ([LoginNewsID], [ImageUrl], [LinkUrl], [Title], [IsActive], [CreatedDate], [CreatedBy], [ModifiedDate], [ModifiedBy]) values (16, N'https://blueplannerstgacc.blob.core.windows.net/loginnewsimage/Spindrift2.jpg', N'https://www.linkedin.com/feed/update/urn:li:activity:6914942640115302400', N'Spindrift sets sail with UpClear for TPM', 1, CAST(N'2022-03-31T14:00:25.537' as DateTime), N'tech@upclear.com', null, null)
set identity_insert [dbo].[LoginNews] off
GO
