# FILEPATH: /home/walter/Desktop/MASTER/PISTL/PISTL/Project/docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      # Connection string for Azure Database
      ConnectionStrings__AzureDatabase: "Server=tcp:pistlserver.database.windows.net,1433;
                                        Initial Catalog=dat;Persist Security Info=False;
                                        User ID=walter;Password=Daniel123;MultipleActiveResultSets=False;
                                        Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend