version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - database
    environment:
      ConnectionStrings__DefaultConnection: "Server=database,1434;Database=DAT;User Id=sa;Password=Daniel123;TrustServerCertificate=true;"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  database:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "1433:1434"
    environment:
      SA_PASSWORD: "Daniel123"
      ACCEPT_EULA: "Y"
      MSSQL_DB_NAME: "DAT"
