SELECT TOP (1000) [LoginID]
      ,[Email]
      ,[Name]
      ,[Password]
      ,[PasswordSalt]
      ,[PasswordModifiedDate]
      ,[PasswordExpirationDate]
      ,[InvalidAttemptCount]
      ,[ResetPasswordEndDate]
      ,[ResetPasswordKey]
      ,[ResetPasswordSentCount]
      ,[ResetPasswordInvalidAttemptCount]
      ,[LastLoginDate]
      ,[TermsAccepted]
      ,[DATEnabled]
      ,[Phone]
      ,[BlockedReason]
      ,[CreatedDate]
      ,[CreatedBy]
      ,[ModifiedDate]
      ,[ModifiedBy]
  FROM [master].[dbo].[Login]