name: NUnit Tests

on:
    push:
        branches:
            - login

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2 

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x

        - name: Restore dependencies
          run: dotnet restore Project/backend/backend.sln

        - name: Build
          run: dotnet build Project/backend/backend.sln --configuration Release

        - name: Build Docker image
          run: docker build -t sql_dat -f Project/docker .

        - name: Run Docker image
          run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Daniel123' -p 1434:1433 --name sql_container sql_dat
          
        - name: NUnit Tests
          run: dotnet test Project/backend/test/test.csproj --no-build --verbosity normal
