name: NUnit Tests

on:
    push:
        branches:
            - login

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2 

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.100

        - name: Restore dependencies
          run: dotnet restore Project/backend/src/Project.csproj

        - name: Build
          run: dotnet build --configuration Release
          
        - name: NUnit Tests
          run: dotnet test --no-build --verbosity normal
